color: null
fieldLayouts:
  f937be92-a2e4-4734-b582-4708785aa73e:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-12-07T12:03:32+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 86cb64b3-7a5b-44a1-af74-4b50524fcd14
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-12-09T10:22:33+00:00'
            elementCondition: null
            fieldUid: 2430aafc-4c3e-46cd-a939-3590fb0bae7b # Gerelateerd aan
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5e9739c9-3681-467d-b525-c6fdfbd6dda1
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-12-07T15:31:06+00:00'
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: 6653fcf2-0c85-4098-ae91-5ce7ac61d88e
            userCondition: null
          -
            dateAdded: '2024-12-07T15:31:06+00:00'
            elementCondition: null
            fieldUid: e39f4ef5-8dec-40fe-83ef-107c617981bc # Page title
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 49398f82-3109-4be2-b819-6f4b72158085
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-12-07T15:31:06+00:00'
            elementCondition: null
            fieldUid: d3cf3f36-3d63-4ce1-976b-b3bdaf15c5b1 # Page description
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0a4101f0-4ba6-4470-acab-c90df610a5c9
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-12-07T15:31:06+00:00'
            elementCondition: null
            fieldUid: b11847cc-da8d-47c7-bba3-200d6e853d6e # Hero image
            handle: pageImage
            includeInCards: false
            instructions: null
            label: 'Page image'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: de731316-319e-429f-88d4-c31a8329ce9a
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-12-07T12:05:04+00:00'
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: 141078ec-b99d-4950-b93d-09fa67346338
            userCondition: null
          -
            dateAdded: '2024-12-07T12:05:04+00:00'
            elementCondition: null
            fieldUid: 28386272-18fb-49fe-a577-621f6e30eab0 # Hero title
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2109fc6c-7239-427c-b8e3-f9a495728d14
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-12-07T12:05:04+00:00'
            elementCondition: null
            fieldUid: b11847cc-da8d-47c7-bba3-200d6e853d6e # Hero image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4f158232-6d95-4a5c-8acb-dd8dce3ee05c
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-12-07T12:05:04+00:00'
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: ce7c67b5-8e14-40f3-851e-8abf31fff31e
            userCondition: null
          -
            dateAdded: '2024-12-07T12:05:04+00:00'
            elementCondition: null
            fieldUid: 9c0fe570-11a0-4087-9cc4-b3f4dae01ea6 # Matrix
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: cb4b4a84-b3f3-4e22-809d-1e103c5f3b45
            userCondition: null
            warning: null
            width: 100
        name: Inhoud
        uid: 8160ea3c-1f7e-44fd-9b4b-2d822526ddfc
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2024-12-07T12:05:04+00:00'
            elementCondition: null
            fieldUid: 7ed5075f-76f4-4d1f-bc63-24574242960c # SEO
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fd67ec20-e054-43a1-bd33-6244ff0e15e8
            userCondition: null
            warning: null
            width: 100
        name: SEO
        uid: 89a2ac3f-c9de-4c25-bbcd-1e20bfd7196f
        userCondition: null
handle: blogDetail
hasTitleField: true
icon: ''
name: 'Page | Blog detail'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: ''
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: ''
titleTranslationMethod: site
