color: null
fieldLayouts:
  238802d5-bff1-44c6-9309-31bb6ed1cb44:
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2024-12-16T20:49:54+00:00'
            elementCondition: null
            fieldUid: c16c87e7-aa54-415e-b8b4-a8d626d68b18 # Adress
            handle: null
            includeInCards: true
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6e224ae6-5848-4e1d-9163-fbecc4706bd5
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-12-16T20:49:54+00:00'
            elementCondition: null
            fieldUid: f548ef62-9b39-4c1f-a81e-d9229958ac0e # Google Maps url
            handle: null
            includeInCards: true
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4323282d-0cf8-45ec-a2f6-87e2195bd02b
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-12-16T20:49:54+00:00'
            elementCondition: null
            fieldUid: d71aabb4-dc67-4f3d-9ef7-b9155c511cba # Website URL
            handle: null
            includeInCards: true
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 43837494-195a-4958-baaa-2dff0df2562a
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-12-16T20:49:54+00:00'
            elementCondition: null
            fieldUid: 06efb1e7-f5d8-4694-8151-7783e392018e # Ticket URL
            handle: null
            includeInCards: true
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ffb6fdc7-16ff-4371-a109-db0a835bc734
            userCondition: null
            warning: null
            width: 100
        name: Inhoud
        uid: 9fe0e75f-030b-4f45-945d-44cfe99b71da
        userCondition: null
handle: clubSettings
hasTitleField: false
icon: ''
name: 'Club settings'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: ''
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: ''
titleTranslationMethod: site
