color: emerald
fieldLayouts:
  a30bd272-f6e5-43b2-9944-86558e828aaf:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: be01f0e7-c7fb-47f1-8127-5d8e47718290
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 28386272-18fb-49fe-a577-621f6e30eab0 # Hero title
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 81bc3e54-b754-4d4a-aba6-8d13594979a4
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 4f4672b8-b625-45df-92a9-c398d1d4cd63 # Hero description
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 78ddbb4a-3331-40a0-b56a-eb5a6900e9ab
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: b11847cc-da8d-47c7-bba3-200d6e853d6e # Hero image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9cc0440c-7166-404a-8a13-4afe486ede56
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: e529eacf-7c43-4b0d-b7a8-124fee4d34de # CTA
            handle: heroCta
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 784707de-07b2-40d8-b791-2d0ff8432ff3
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: 723a3112-40d1-48bf-ab15-1ebf4c292e9a
            userCondition: null
          -
            elementCondition: null
            fieldUid: 9c0fe570-11a0-4087-9cc4-b3f4dae01ea6 # Matrix
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 65374beb-0207-4eba-8d81-ea45e0ae4b62
            userCondition: null
            warning: null
            width: 100
        name: Inhoud
        uid: afa7a5ca-fe77-45c8-ae27-8ef7fc68cebb
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 7ed5075f-76f4-4d1f-bc63-24574242960c # SEO
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: bfaf4392-6682-4ac9-86a1-534db66e0081
            userCondition: null
            warning: null
            width: 100
        name: SEO
        uid: b1f2c1ac-fcae-484d-b1b8-44e46b96e299
        userCondition: null
handle: contentPage
hasTitleField: true
icon: pencil
name: 'Content page'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: ''
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: ''
titleTranslationMethod: site
