color: null
fieldLayouts:
  c950c5e4-9221-41a0-99c4-7aea5640e849:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-12-16T11:32:08+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 6f4da3ac-bbdb-4276-b28f-fca213ec608d
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-12-16T11:33:53+00:00'
            elementCondition: null
            fieldUid: 79372943-5d5e-4ce9-8fca-001ceaeda8d5 # Description
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 33403487-67d9-41ea-98d1-d402c508aea8
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-12-16T11:33:53+00:00'
            elementCondition: null
            fieldUid: 3c7ea62a-0e10-4dca-889c-eb4f178473d6 # Entry
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ec434b4c-4ebb-4321-a0ba-5482fbe51ebb
            userCondition: null
            warning: null
            width: 100
        name: Inhoud
        uid: 9b57d257-6e07-4cb4-9f12-c2f8a323cc37
        userCondition: null
handle: infoCard
hasTitleField: true
icon: ''
name: 'Info card'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: ''
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: ''
titleTranslationMethod: site
