color: green
fieldLayouts:
  11b1537e-848e-41a6-96fa-f302bff4cbaa:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-12-16T11:24:09+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 17aa0131-fca2-4304-91ee-b0a2d7204d7b
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-12-16T11:24:09+00:00'
            elementCondition: null
            fieldUid: 4510a52c-d2a5-480a-9139-61207c1c0b48 # Image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7a45ab3b-bdf9-41dc-8e8c-58679b4623d8
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-12-16T11:24:09+00:00'
            elementCondition: null
            fieldUid: 7863f077-25df-46a0-919f-e5ff5e3a8142 # Image description
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f71163b1-2969-4766-9150-352bcbbb31b5
            userCondition: null
            warning: null
            width: 100
        name: Inhoud
        uid: 9910f03c-fe3e-4cbb-bc19-3544228ceb02
        userCondition: null
handle: matrixImage
hasTitleField: true
icon: ''
name: 'Matrix | Image'
showSlugField: false
showStatusField: false
slugTranslationKeyFormat: ''
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: ''
titleTranslationMethod: site
