color: green
fieldLayouts:
  8d4c7b07-0872-460a-b9a5-24e86f0532a6:
    cardView:
      - slug
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2024-12-28T12:11:37+00:00'
            elementCondition: null
            fieldUid: 66cd225f-fdb6-49e8-9603-d8cb527c2ff1 # Content cards
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 31d0db9e-e3b8-458b-afa0-32d8ef731c8f
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-12-16T11:34:04+00:00'
            elementCondition: null
            fieldUid: 66c3e5d1-0a34-40db-b67a-6794ee6defb5 # Info cards
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fc90cc82-118e-4484-8c74-8cc7790555f5
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-12-16T09:41:03+00:00'
            elementCondition: null
            fieldUid: e4183bb3-fc84-4eee-b49f-dae1a173e0d9 # Square cards
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d76c17c6-4eca-49ec-84d3-0e7845028cdb
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-12-28T12:04:42+00:00'
            elementCondition: null
            fieldUid: bcbc1e73-a8c3-408c-8dae-7d385271d68b # Landscape Cards
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 718670fa-7686-4ef8-8d93-67f907eee3f3
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-12-28T15:17:52+00:00'
            elementCondition: null
            fieldUid: e529eacf-7c43-4b0d-b7a8-124fee4d34de # CTA
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4767373b-526f-4625-9555-25d2dc254bc9
            userCondition: null
            warning: null
            width: 100
        name: Inhoud
        uid: 07a82194-979e-4059-8bde-5cbfeacabce5
        userCondition: null
handle: matrixCards
hasTitleField: false
icon: ''
name: 'Matrix | Cards'
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: ''
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: ''
titleTranslationMethod: site
