color: null
fieldLayouts:
  8d4c7b07-0872-460a-b9a5-24e86f0532a6:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-12-16T09:35:41+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 7ebdfe41-7086-4b6d-8733-a80e9a1e3bb4
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-12-16T09:47:28+00:00'
            elementCondition: null
            fieldUid: 79372943-5d5e-4ce9-8fca-001ceaeda8d5 # Description
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 91829a4f-9469-4946-81ef-4fcf762aeb6d
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-12-16T09:41:03+00:00'
            elementCondition: null
            fieldUid: e4183bb3-fc84-4eee-b49f-dae1a173e0d9 # Square cards
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d76c17c6-4eca-49ec-84d3-0e7845028cdb
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-12-16T11:34:04+00:00'
            elementCondition: null
            fieldUid: 66c3e5d1-0a34-40db-b67a-6794ee6defb5 # Info cards
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fc90cc82-118e-4484-8c74-8cc7790555f5
            userCondition: null
            warning: null
            width: 100
        name: Inhoud
        uid: 07a82194-979e-4059-8bde-5cbfeacabce5
        userCondition: null
handle: matrixCards
hasTitleField: true
icon: ''
name: 'Matrix | Cards'
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: ''
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: ''
titleTranslationMethod: site
