color: null
fieldLayouts:
  5a98db19-f5e1-440d-bed3-b3a7af234c55:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-12-09T18:58:43+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 004d8444-2e5b-4c9b-9289-935ccdaab577
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-12-09T19:00:17+00:00'
            elementCondition: null
            fieldUid: 3ab17238-f0e4-4956-926a-fdd94ceb7837 # Related entry
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d265e2f9-17ac-4cb3-a786-6f680b4ddf9c
            userCondition: null
            warning: null
            width: 100
        name: Inhoud
        uid: 70373b18-71a3-4388-a25d-de72b8c6d249
        userCondition: null
handle: matrixRelatedPost
hasTitleField: true
icon: ''
name: 'Matrix | Related post'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: ''
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: ''
titleTranslationMethod: site
