color: green
fieldLayouts:
  7ee225f6-e6a3-457a-b906-8c38a085ff9f:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-12-17T13:07:41+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: f4944511-826c-49a3-9d5d-90ddc5e5979a
            userCondition: null
            warning: null
            width: 100
        name: Inhoud
        uid: 20fbc223-03d4-44c9-8fcf-db30f9edb2e8
        userCondition: null
handle: matrixUitgaanDetailOverview
hasTitleField: true
icon: ''
name: 'Matrix | Uitgaan detail overview'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: ''
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: ''
titleTranslationMethod: site
