color: null
fieldLayouts:
  579dda3b-c9be-4af0-98b4-ad5b7a02959f:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: f1cd08e5-90bc-47b8-b02d-011f0a5c3e10
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 3d4370d8-2bc1-4dd4-b518-30aaacc5b408 # Navigation link
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5e26acc6-7ea5-4b58-8caf-395a5e2a1ca6
            userCondition: null
            warning: null
            width: 100
        name: Inhoud
        uid: fe32953f-8465-4ced-925e-7db14fbdf849
        userCondition: null
handle: navigation
hasTitleField: true
icon: list-tree
name: Navigation
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: ''
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: ''
titleTranslationMethod: site
