color: yellow
fieldLayouts:
  3bc32cf1-7e8c-43b8-ac8f-a6a16bc543e8:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: a9237fe8-258a-48a1-8191-2f25a411958a
            userCondition: null
            warning: null
            width: 100
        name: Inhoud
        uid: 2ed79de2-77af-47c9-80f2-4b12ea33ac0e
        userCondition: null
handle: siteTheme
hasTitleField: false
icon: palette
name: 'Site theme'
showSlugField: false
showStatusField: false
slugTranslationKeyFormat: ''
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: ''
titleTranslationMethod: site
