color: null
fieldLayouts:
  ae541704-a1f2-4576-8bff-fa8a288c6e61:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-12-16T09:36:44+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: 'Overschrijft de relatie title'
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 15f84ee6-60a9-4c83-b053-40a2911eb110
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-12-16T09:40:28+00:00'
            elementCondition: null
            fieldUid: b9277aaa-c0ce-4c6d-85fd-59961c503c7d # Subtitle
            handle: null
            includeInCards: true
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f7cb9e65-f09c-4300-9cad-e8873de7f88e
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-12-16T09:40:28+00:00'
            elementCondition: null
            fieldUid: 3c7ea62a-0e10-4dca-889c-eb4f178473d6 # Entry
            handle: null
            includeInCards: true
            instructions: 'Wordt gebruikt voor het ophalen van de zichtbare gegevens en de URL, kan worden overschreven door het veld Title en Subtitle te gebruiken.'
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 100d7392-debe-423c-9124-031d468ef5a7
            userCondition: null
            warning: null
            width: 100
        name: Inhoud
        uid: 037155ef-f71e-4804-99b4-214e8e53b33f
        userCondition: null
handle: squareCard
hasTitleField: true
icon: ''
name: 'Square card'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: ''
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: ''
titleTranslationMethod: site
