color: blue
fieldLayouts:
  d7a74b93-5c72-4593-8a99-dc72b08509b9:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-12-28T12:04:27+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: b2788771-c160-4e5d-a5e2-dccb9739b64b
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-12-28T12:06:08+00:00'
            elementCondition: null
            fieldUid: 79372943-5d5e-4ce9-8fca-001ceaeda8d5 # Description
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9bd4ade5-3415-4c3b-912a-7f675525ba32
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-12-28T12:06:08+00:00'
            elementCondition: null
            fieldUid: 3c7ea62a-0e10-4dca-889c-eb4f178473d6 # Entry
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b3f9c2e8-19dd-410d-a87e-3ac71225dc38
            userCondition: null
            warning: null
            width: 100
        name: Inhoud
        uid: 8c3da52d-16e1-4bd6-90a1-bd30d4ae41fe
        userCondition: null
handle: typeContentCard
hasTitleField: true
icon: ''
name: 'Type | Content card'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: ''
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: ''
titleTranslationMethod: site
