color: orange
fieldLayouts:
  46e1c0ca-b8b5-404d-8b61-adddefecca27:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-12-17T12:38:16+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 135bdaa6-6e31-484b-8416-21ea152895da
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-12-17T12:40:13+00:00'
            elementCondition: null
            fieldUid: e39f4ef5-8dec-40fe-83ef-107c617981bc # Page title
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 724f4d36-55fe-4d58-a584-bac348d9cde0
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-12-17T12:40:13+00:00'
            elementCondition: null
            fieldUid: d3cf3f36-3d63-4ce1-976b-b3bdaf15c5b1 # Page description
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 78a12fa3-8688-44a7-933e-cbf16e77a5d9
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-12-17T12:40:13+00:00'
            elementCondition: null
            fieldUid: b11847cc-da8d-47c7-bba3-200d6e853d6e # Hero image
            handle: pageImage
            includeInCards: false
            instructions: null
            label: 'Page image'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2b46a39a-8256-463d-868e-88f6ed5542ce
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-12-17T12:40:13+00:00'
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: cd37a8a4-6a61-4488-922c-93787648bb48
            userCondition: null
          -
            dateAdded: '2024-12-17T12:40:13+00:00'
            elementCondition: null
            fieldUid: 28386272-18fb-49fe-a577-621f6e30eab0 # Hero title
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: adf18300-edcc-4254-a997-73a1b95b7fcd
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-12-17T12:40:13+00:00'
            elementCondition: null
            fieldUid: 4f4672b8-b625-45df-92a9-c398d1d4cd63 # Hero description
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 77ed5d38-3fc8-42f5-9f57-79f5f4979ad2
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-12-17T12:40:13+00:00'
            elementCondition: null
            fieldUid: b11847cc-da8d-47c7-bba3-200d6e853d6e # Hero image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: effc2641-4596-4579-8106-7f7873e6c865
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-12-17T12:40:13+00:00'
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: 9f5ffc95-2a3b-4363-b900-263f924d6914
            userCondition: null
          -
            dateAdded: '2024-12-17T12:40:13+00:00'
            elementCondition: null
            fieldUid: 9c0fe570-11a0-4087-9cc4-b3f4dae01ea6 # Matrix
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5507d848-686a-442a-aa56-32ec60c725e8
            userCondition: null
            warning: null
            width: 100
        name: Inhoud
        uid: edbf78bd-ada8-4599-81c9-2aa8443d27a1
        userCondition: null
handle: uitgaanOverview
hasTitleField: true
icon: ''
name: 'Page type | Uitgaan overview'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: ''
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: ''
titleTranslationMethod: site
