color: orange
fieldLayouts:
  d456bacc-ac5c-46bf-80cc-5f5608232e3b:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-12-16T20:46:18+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: b8ea0789-0d93-431e-be0a-24a0e25c331f
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-12-16T20:50:15+00:00'
            elementCondition: null
            fieldUid: cf788f76-ff1e-44e5-a8a6-e68675ee1250 # Club images
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fb1c180c-f522-4823-b595-269a742803dd
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-12-16T20:50:15+00:00'
            elementCondition: null
            fieldUid: 63293651-1dad-45a2-a40a-3a8e3a5bcf7a # Club config
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a9e985a8-ee37-4176-9904-4998cc89f9ed
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-12-16T20:50:15+00:00'
            elementCondition: null
            fieldUid: 9c0fe570-11a0-4087-9cc4-b3f4dae01ea6 # Matrix
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b674d469-e727-4f1b-92ba-3251d89a6b67
            userCondition: null
            warning: null
            width: 100
        name: Inhoud
        uid: fa145f2b-329e-4d29-972f-4fd01a3e4bf4
        userCondition: null
handle: uitgaanDetail
hasTitleField: true
icon: ''
name: 'Page type | Uitgaan detail'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: ''
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: ''
titleTranslationMethod: site
