color: null
fieldLayouts:
  40728e32-c1cd-4f28-88a7-77b615bb782a:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-12-28T17:44:25+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 642b9cec-3bed-484a-a0b2-d641906ac23f
            userCondition: null
            warning: null
            width: 100
        name: Inhoud
        uid: 3554f284-d02b-4dfd-8193-08e5b8cfeefa
        userCondition: null
handle: usp
hasTitleField: true
icon: ''
name: USP
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: ''
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: ''
titleTranslationMethod: site
