headingLevels:
  - 1
  - 2
  - 3
  - 4
  - 5
  - 6
name: 'Page body'
toolbar:
  - heading
  - '|'
  - bold
  - italic
  - underline
  - strikethrough
  - '|'
  - bulletedList
  - numberedList
  - outdent
  - indent
  - '|'
  - insertTable
  - link
  - '|'
  - pageBreak
  - '|'
  - createEntry
