baseUrl: $ALBUFERIA_NL
enabled: '1'
handle: albufeiraNL
hasUrls: true
language: nl-NL
name: 'YouthBreaks NL - Albufeira'
primary: false
siteGroup: f2b78056-d43b-4b41-93dc-57fef1d1975d # YouthBreaks NL
sortOrder: 2
