baseUrl: $ALBUFERIA_EN
enabled: '1'
handle: albufeiraEN
hasUrls: true
language: en
name: 'YouthBreaks EN - albufeira'
primary: false
siteGroup: 616e4fd4-0f3f-428b-96b5-3ae84ffb392d # YouthBreaks EN
sortOrder: 5
