baseUrl: $CHERSONISSOS_NL
enabled: '1'
handle: chersonissosNL
hasUrls: true
language: nl-NL
name: 'YouthBreaks NL - Chersonissos'
primary: false
siteGroup: f2b78056-d43b-4b41-93dc-57fef1d1975d # YouthBreaks NL
sortOrder: 6
