altTranslationKeyFormat: null
altTranslationMethod: site
fieldLayouts:
  fd45377c-b133-4618-8197-31e85f75407e:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-12-07T13:20:58+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: a66256c4-9c6d-472a-9a34-91194e7c631b
            userCondition: null
            warning: null
            width: 100
          -
            attribute: alt
            class: null
            cols: null
            dateAdded: '2024-12-07T13:20:58+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            instructions: null
            label: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: true
            required: false
            rows: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AltField
            uid: 53e44a96-2288-4781-9042-aeec6f6dad78
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-12-07T13:22:12+00:00'
            elementCondition: null
            fieldUid: e4d3d6ad-aef0-4a56-80e1-b2e942135a5a # Source
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5549fd19-0ae3-4b62-a043-4c1b744f6dff
            userCondition: null
            warning: null
            width: 100
        name: Inhoud
        uid: 5471e0ba-7733-4fe8-b0d6-9c41d266478e
        userCondition: null
fs: local
handle: local
name: Local
sortOrder: 1
subpath: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
