altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  35206c3f-3c82-478b-b3da-649dd2881404:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-12-16T12:44:36+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: b3ab4336-b05c-4dc9-b338-fb498ae67976
            userCondition: null
            warning: null
            width: 100
          -
            attribute: alt
            class: null
            cols: null
            dateAdded: '2024-12-16T12:45:54+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            instructions: null
            label: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: true
            required: false
            rows: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AltField
            uid: 51af9b53-732f-4b81-82a1-22008d0a4f17
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-12-16T12:45:54+00:00'
            elementCondition: null
            fieldUid: e4d3d6ad-aef0-4a56-80e1-b2e942135a5a # Source
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: cd3716b7-67eb-4070-aec7-64c680f49452
            userCondition: null
            warning: null
            width: 100
        name: Inhoud
        uid: f4284766-9301-4cb1-be4a-888f35772ca7
        userCondition: null
fs: r2Chersonissos
handle: r2Chersonissos
name: 'R2 Chersonissos'
sortOrder: 4
subpath: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
