columnSuffix: null
handle: clubUsps
instructions: null
name: 'Club usp''s'
searchable: false
settings:
  createButtonLabel: null
  defaultIndexViewMode: cards
  entryTypes:
    - c08e90d5-0a00-4bf4-8be6-d1d6caf7fe67 # USP
  includeTableView: false
  maxEntries: null
  minEntries: null
  pageSize: null
  propagationKeyFormat: null
  propagationMethod: all
  showCardsInGrid: false
  viewMode: blocks
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
