columnSuffix: null
handle: landscapeCards
instructions: null
name: 'Landscape Cards'
searchable: false
settings:
  createButtonLabel: null
  defaultIndexViewMode: cards
  entryTypes:
    - 72dced8e-04ec-481f-8fbb-72921e2ac568 # Type | Landscape Card
  includeTableView: false
  maxEntries: null
  minEntries: null
  pageSize: null
  propagationKeyFormat: null
  propagationMethod: all
  showCardsInGrid: false
  viewMode: blocks
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
