columnSuffix: null
handle: siteColor
instructions: 'Bijvoorbeeld ''green'' of ''pink'''
name: 'Site color'
searchable: false
settings:
  defaultColor: null
  presets:
    - '#369bed'
    - '#ed3636'
    - '#ed6a36'
    - '#155182'
    - '#edb936'
translationKeyFormat: null
translationMethod: none
type: craft\fields\Color
