defaultPlacement: end
enableVersioning: true
entryTypes:
  - 7d26659a-16fd-4fbd-b167-a8a5e832265f # Home
handle: home
maxAuthors: 1
name: Home
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primaire invoer-pagina'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  1fa00b89-1304-4bcc-b401-99ad445d9241: # YouthBreaks EN
    enabledByDefault: true
    hasUrls: true
    template: pages/home/_index
    uriFormat: __home__
  86aa91de-bde7-44da-8bd5-d29a95b3f28c: # YouthBreaks EN - Lloret de mar
    enabledByDefault: true
    hasUrls: true
    template: pages/home/_index
    uriFormat: __home__
  1643ba74-6496-465b-8193-45ec88e23cd7: # YouthBreaks NL - Albufeira
    enabledByDefault: true
    hasUrls: true
    template: pages/home/_index
    uriFormat: __home__
  9620f8bc-de2f-4a52-ac63-94cba3bed665: # YouthBreaks
    enabledByDefault: true
    hasUrls: true
    template: pages/home/_index
    uriFormat: __home__
  81132275-2a11-4ee2-b595-4ed825b4d827: # YouthBreaks EN - albufeira
    enabledByDefault: true
    hasUrls: true
    template: pages/home/_index
    uriFormat: __home__
  c58ce353-a590-49b2-93a4-f2abd4f104f3: # YouthBreaks NL - Lloret de Mar
    enabledByDefault: true
    hasUrls: true
    template: pages/home/_index
    uriFormat: __home__
type: single
