defaultPlacement: end
enableVersioning: true
entryTypes:
  - b9723ca6-1d73-46e2-a144-756cd3e36e11 # Navigation
handle: navigation
maxAuthors: 1
name: Navigation
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primaire invoer-pagina'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: none
siteSettings:
  1fa00b89-1304-4bcc-b401-99ad445d9241: # YouthBreaks EN
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
  86aa91de-bde7-44da-8bd5-d29a95b3f28c: # YouthBreaks EN - Lloret de mar
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
  1643ba74-6496-465b-8193-45ec88e23cd7: # YouthBreaks NL - Albufeira
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
  9620f8bc-de2f-4a52-ac63-94cba3bed665: # YouthBreaks
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
  81132275-2a11-4ee2-b595-4ed825b4d827: # YouthBreaks EN - albufeira
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
  c58ce353-a590-49b2-93a4-f2abd4f104f3: # YouthBreaks NL - Lloret de Mar
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
structure:
  maxLevels: null
  uid: 40a798e7-8e98-4326-a61a-7c427138376d
type: structure
