defaultPlacement: end
enableVersioning: true
entryTypes:
  - b64b022d-84d7-4811-985f-fd1f0acff9bc # Page type | Uitgaan overview
handle: uitgaanOverview
maxAuthors: 1
name: 'Uitgaan overview'
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primaire invoer-pagina'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  1643ba74-6496-465b-8193-45ec88e23cd7: # YouthBreaks NL - Albufeira
    enabledByDefault: true
    hasUrls: true
    template: pages/uitgaan/_index
    uriFormat: uitgaan
  ab7b1962-e0cf-44f5-a096-7aec91ca594f: # YouthBreaks NL - Mallorca
    enabledByDefault: true
    hasUrls: true
    template: pages/uitgaan/_index
    uriFormat: uitgaan
  c58ce353-a590-49b2-93a4-f2abd4f104f3: # YouthBreaks NL - Lloret de Mar
    enabledByDefault: true
    hasUrls: true
    template: pages/uitgaan/_index
    uriFormat: uitgaan
  df6abb26-4ba5-4637-9534-1d06011bf708: # YouthBreaks NL - Chersonissos
    enabledByDefault: true
    hasUrls: true
    template: pages/uitgaan/_index
    uriFormat: uitgaan
type: single
